language: c

compiler:
  - gcc
  - clang

install:
 - sudo apt-get install libconfig8-dev
 - sudo apt-get install libreadline6-dev
 - sudo apt-get install libssl-dev
 - sudo apt-get install liblua5.2-dev lua5.2
 - sudo apt-get install libevent-dev

script:
  - ./configure
  - make auto/constants.h
  - cat auto/constants.h
  - make
